apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-certificate
  namespace: argocd
spec:
  secretName: argocd-server-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
  - "argocd.minikube.com"
  issuerRef:
    name: argocd-ca-issuer
